// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package config

type Config struct {
	Db struct {
		Path string `json:"path"`
	} `json:"db"`

	Imap struct {
		Host string `json:"host"`

		Port int64 `json:"port"`

		CatchAllUsername string `json:"catch_all_username"`

		CatchAllPassword string `json:"catch_all_password"`

		Mbox string `json:"mbox"`

		UseTls bool `json:"use_tls"`
	} `json:"imap"`

	Crawler struct {
		Endpoints struct {
			HomeUrl string `json:"home"`

			RegisterEndpoint string `json:"register"`

			LoginEndpoint string `json:"login"`

			SearchEndpoint string `json:"search"`

			SettingsBillingEndpoint string `json:"settings_billing_plan"`
		} `json:"endpoints"`

		Agents struct {
			Templates struct {
				EmailTemplate string `json:"email"`

				PasswordTemplate string `json:"password"`

				OrganizationTemplate string `json:"organization"`

				FirstNameTemplate string `json:"first_name"`

				LastNameTemplate string `json:"last_name"`
			} `json:"templates"`

			MaxAgents int64 `json:"max_agents"`
		} `json:"agents"`

		BrowserBinaryPath string `json:"browser_binary_path"`

		VirtualDisplay bool `json:"virtual_display"`
	} `json:"crawler"`

	Logger LoggerConfig `json:"logger"`

	Preferences Preferences `json:"preferences"`
}

type LoggerConfig struct {
	Verbose bool `json:"verbose"`

	NoColor bool `json:"no_color"`

	ShowCaller bool `json:"show_caller"`

	Dir string `json:"dir"`

	MaxSizeMb int64 `json:"max_size_mb"`

	MaxBackups int64 `json:"max_backups"`

	MaxAgeDays int64 `json:"max_age_days"`

	LogName string `json:"log_name"`
}

type Preferences struct {
	Theme string `json:"theme"`

	Language string `json:"language"`

	AccentMode string `json:"accent_mode"`

	AccentColor string `json:"accent_color"`
}

type ThemeMode string

type LocaleCode string

type AccentMode string
