// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package config

type Config struct {
	Db struct {
		Path string `json:"path"`
	} `json:"db"`

	Imap struct {
		Host string `json:"host"`

		Port int64 `json:"port"`

		CatchAllUsername string `json:"catch_all_username"`

		CatchAllPassword string `json:"catch_all_password"`

		Mbox string `json:"mbox"`

		UseTls bool `json:"use_tls"`
	} `json:"imap"`

	Scraper struct {
		QueryStrings []any/* CUE closed list */ `json:"custom_query_strings"`

		Endpoints struct {
			HomeEndpoint string `json:"home"`

			RegisterEndpoint string `json:"register"`

			LoginEndpoint string `json:"login"`

			SearchEndpoint string `json:"search"`

			SettingsBillingEndpoint string `json:"settings_billing_plan"`
		} `json:"endpoints"`

		Agents struct {
			Templates struct {
				EmailTemplate string `json:"email"`

				PasswordTemplate string `json:"password"`

				OrganizationTemplate string `json:"organization"`

				FirstNameTemplate string `json:"first_name"`

				LastNameTemplate string `json:"last_name"`
			} `json:"templates"`

			MaxAgents int64 `json:"max_agents"`

			MaxRegisterRetries int64 `json:"max_register_retries"`
		} `json:"agents"`

		BrowserBinaryPath string `json:"browser_binary_path"`

		VirtualDisplay bool `json:"virtual_display"`

		MinimalBrowser bool `json:"minimal_browser"`
	} `json:"scraper"`

	Scanner struct {
		PingMode string `json:"ping_mode"`

		IcmpPing bool `json:"icmp_ping"`

		RejectBlankScreenshots bool `json:"reject_blank_screenshots"`

		Workers struct {
			PingTimeoutSeconds int64 `json:"ping_timeout_seconds"`

			ConnectTimeoutSeconds int64 `json:"connect_timeout_seconds"`

			BannerTimeoutSeconds int64 `json:"banner_timeout_seconds"`

			ScreenshotTimeoutSeconds int64 `json:"screenshot_timeout_seconds"`

			ScreenshotDelaySeconds int64 `json:"screenshot_delay_seconds"`

			ScreenshotPauseSeconds int64 `json:"screenshot_pause_seconds"`

			ScreenshotMaxWorkers int64 `json:"screenshot_max_workers"`

			MaxWorkers int64 `json:"max_workers"`
		} `json:"workers"`

		Templates struct {
			VncCommandTemplate string `json:"vnc_command"`

			RdpCommandTemplate string `json:"rdp_command"`

			SpiceCommandTemplate string `json:"spice_command"`

			SshCommandTemplate string `json:"ssh_command"`

			HttpCommandTemplate string `json:"http_command"`

			HttpsCommandTemplate string `json:"https_command"`

			ScreenshotCommandTemplate string `json:"screenshot_command"`
		} `json:"templates"`
	} `json:"scanner"`

	Logger LoggerConfig `json:"logger"`

	Preferences Preferences `json:"preferences"`
}

type LoggerConfig struct {
	Verbose bool `json:"verbose"`

	NoColor bool `json:"no_color"`

	ShowCaller bool `json:"show_caller"`

	Dir string `json:"dir"`

	MaxSizeMb int64 `json:"max_size_mb"`

	MaxBackups int64 `json:"max_backups"`

	MaxAgeDays int64 `json:"max_age_days"`

	LogName string `json:"log_name"`

	FrontendConsoleLog bool `json:"frontend_console_log"`
}

type Preferences struct {
	Theme string `json:"theme"`

	Language string `json:"language"`

	AccentMode string `json:"accent_mode"`

	AccentColor string `json:"accent_color"`

	CloseToTray bool `json:"close_to_tray"`

	MemoryUnit string `json:"memory_unit"`
}

type ThemeMode string

type LocaleCode string

type AccentMode string

type MemoryUnit string
